[general]
  # debug = false
  # log_level = "debug" # info, debug
  # demo_mode = false

[web]
  # host = "0.0.0.0"
  # port = 5665

[locale]
  # date_format = "%d %B %Y"
  # time_format = "%H:%M"

[defaults]
  # image_width = 800
  # image_height = 480

[outputs]
  # [outputs.0]
  #   image_path = "images/samples"
  #   show_date = false
  #   show_time = false
  # [outputs.1]
  #   ...
  # [outputs.2]
  #   ...

[mqtt]
  # host = "hass.local"
  # port = 1883
  # user = "user"
  # password = "password"
  # keepalive = 60
  # log_messages = false

[mqtt.topic_prefix]
  # app = "inkyframeweb"

[mqtt.topic_prefix.homeassistant]
  # default = "homeassistant"
  # statestream = "homeassistant/statestream"
