[general]
  # debug = false
  # log_level = "debug" # info, debug

[web]
  # host = "0.0.0.0"
  # port = 5665

[locale]
  # date_format = "%d %B %Y"
  # time_format = "%H:%M"

[display]
  # Inky Frame 7.3: 800w x 480h
  # width = 800
  # height = 480

[outputs]
  # [outputs.0]
  #   name = "inkyframe7"
  #   width = 800
  #   height = 480
  #   image_path = "images/samples"
  #   delay = 600
  # [outputs.1]
  #   ...
  # [outputs.2]
  #   ...


[mqtt]
  # host = "hass.local"
  # port = 1883
  # user = "user"
  # password = "password"
  # keepalive = 60
  # log_messages = false

[mqtt.topic_prefix]
  # app = "inkyframeweb"

[mqtt.topic_prefix.homeassistant]
  # default = "homeassistant"
  # statestream = "homeassistant/statestream"
